name: Node.js CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
strategy:
  matrix:
    node-version: [10.x, 12.x, 14.x]
steps:
   - name: Checkout code
      uses: actions/checkout@v2
      
   - name: Install dependencies and build
      run: |
        npm install
        npm run build
